### PR TITLE
Fixes roleset bindings for BigQuery datasets

### LINKED ISSUE #96: unsupported resource type: projects/datasets while creating gcp secret roleset with bigquery binding
When I try to create a Vault GCP Secret Engine Roleset on a BigQuery Dataset, it throws "unsupported resource type: projects/datasets" error. I'm stuck on this weird error. What is the root cause?
I can see that in the below page, bigquery datasets can be added to a roleset's binding with the full resource name, but it did not work.
https://www.vaultproject.io/docs/secrets/gcp#roleset-bindings 

```
resource "vault_gcp_secret_roleset" "dataset_access_key_test" {
  backend     = vault_gcp_secret_backend.gcp.path
  roleset     = var.roleset_name
  secret_type = "service_account_key"
  project     = var.project_id
  binding {
    # Here I've tried both the self_link attribute of the dataset and the full resource name like below. Neither of them worked.
    resource = "//bigquery.googleapis.com/projects/${var.project_id}/datasets/${var.dataset_id}"
    roles    = ["roles/bigquery.dataViewer"]
  }
}
```

Command output below:
vault_gcp_secret_roleset.<roleset_name>: Creating...

Error: Error writing GCP Secrets backend roleset "gcp/roleset/<roleset_name>": Error making API request.

URL: PUT https://<vault-url>/v1/gcp/roleset/<roleset_name>
Code: 400. Errors:

* 2 errors occurred:
	* errors from both primary and secondary; primary error was invalid resource "//bigquery.googleapis.com/projects/<project_id>/datasets/<dataset_id>": unsupported resource type: projects/datasets; secondary errors follow
	* invalid resource "//bigquery.googleapis.com/projects/<project_id>/datasets/<dataset_id>": unsupported resource type: projects/datasets

### PR DESCRIPTION
**Pull request by austingebauer**
## Overview

This PR fixes roleset [bindings](https://www.vaultproject.io/api-docs/secret/gcp#bindings) scoped to BigQuery datasets. There was a typo in the switch case when detecting the key type of the resource. You can see that the correct key is `projects/datasets` on [resource_overrides.go#L12](https://github.com/hashicorp/vault-plugin-secrets-gcp/blob/main/plugin/iamutil/internal/resource_overrides.go#L12).

Fixes #96
Fixes https://github.com/hashicorp/vault/issues/10923

## Testing

I manually tested that the service account principal created for the Vault roleset has the "BigQuery Data Viewer" scoped to the specified BigQuery dataset.

The following bindings were used:
```
vault write gcp/roleset/bigquery-binding \
    project="austin-gebauer" \
    secret_type="service_account_key"  \
    bindings=-<<EOF
    resource "//bigquery.googleapis.com/projects/austin-gebauer/datasets/test_vault_bindings_dataset" {
     	roles = [
            "roles/bigquery.dataViewer",
        ]
    }
EOF
```

### CODE REVIEW

**Review by calvn — APPROVED** [review]

**Review by jasonodonnell — DISMISSED** [review]

**Comment by fairclothjm** [comment]
Does this also need to be changed to "datasets"?

https://github.com/hashicorp/vault-plugin-secrets-gcp/blob/565a54711f18bea50dce8225602f112a78afbb40/plugin/iamutil/dataset_resource_test.go#L214

**Comment by calvn** [comment]
@fairclothjm I think that's fine/intended since it's for mapping datasets->dataset.. which is specific to `gcputil.RelativeResourceName`?

File: plugin/iamutil/resource_parser_test.go [hunk 1]
```diff
@@ -39,8 +39,10 @@ func TestEnabledIamResources_RelativeName(t *testing.T) {
 			}
 
 			if resource != nil {
-				if err = verifyResource(resourceType, resource.(*IamResource)); err != nil {
-					t.Errorf("could not verify resource for relative resource name %q: %sv", testRelName, err)
+				if r, ok := resource.(*IamResource); ok {
```
Comment (calvn) [inline plugin/iamutil/resource_parser_test.go:42]: I wonder if we should modify or add a new test that verifies `DatasetResource` from the `generatedResources` collection, or at least verify that `Parse` can return that object of that type to get code coverage on the fix.

**Review by calvn — APPROVED** [review]
One comment around the test. Nice find!

File: plugin/iamutil/resource_parser_test.go (hunk 1 above)
Comment (austingebauer) [reply plugin/iamutil/resource_parser_test.go:42]: Good call. Looking at the existing coverage. Will add a test here if needed 👍

**Comment by austingebauer** [comment]
Not sure why pushing commits keeps dismissing reviews..

**Comment by austingebauer** [comment]
@fairclothjm - You're right that it should be `projects/datasets` there. Confirmed with debugger that `RelativeResourceName.TypeKey` matches the `RestResource.TypeKey` when creating a roleset. This is true for both `IamResource` and `DatasetResource`. Updated in 485c761.

File: plugin/iamutil/resource_parser_test.go (hunk 1 above)
Comment (austingebauer) [reply plugin/iamutil/resource_parser_test.go]: Updated these tests to add coverage for both IAM and dataset resources in 9ce72d1. Used the Resource interface so that both can be used.

**Review by calvn — APPROVED** [review]
