### PR TITLE
Ensure service accounts are fully propagated in GCP before creating IAM bindings 

### LINKED ISSUE #237: [roleset] unable to set IAM policy for resource ... service account does not exist
There appears to be an issue with Google's API where it creates a service account, but it doesn't actually exist when Vault tries to assign it to an IAM Policy (#thxg00g).

The error from terraform looks like:

```
│ Error: Error updating GCP Secrets backend roleset "gcp/roleset/jenkins-finclear-df-x3yi": Error making API request.
│ 
│ URL: PUT https://vault-rops.company.com/v1/gcp/roleset/jenkins-finclear-df-x3yi
│ Code: 400. Errors:
│ 
│ * unable to set IAM policy for resource "//cloudresourcemanager.googleapis.com/projects/rops-finclear-df-rev-p-x3yi": unable to set policy: googleapi: Error 400: Service account vaultjenkins-fincle-1735057926@rops-finclear-df-rev-p-x3yi.iam.gserviceaccount.com does not exist.
│ 
│   with module.project_p.vault_gcp_secret_roleset.jenkins_dataflow,
│   on project/jenkins.tf line 2, in resource "vault_gcp_secret_roleset" "jenkins_dataflow":
│    2: resource "vault_gcp_secret_roleset" "jenkins_dataflow" {
```

I assume that Vault asked the Google API to create a service account, and got back a good response, then when it attempted to assign it to the project IAM policy, it failed stating that it doesn't exist. When we do this with terraform directly (non-vault), we can hit retry, and the second time through, the service account will exist, but with Vault GCP Secrets rolesets, it seems to ~~cleanup~~ forget about the failed service account, which then means that it tries to create a new service account each time.

Getting Google to stop doing these asynchronous operations is likely a lost cause, so maybe there should be a bit of a retry loop on the code that assigns IAM Policies when it sees the error that the service account does not exist (_yet_).

~tommy

### PR DESCRIPTION
**Pull request by vinay-gopalan**
# Overview
Service Accounts in GCP could take 60seconds or more to be ready to use (see docs [here](https://cloud.google.com/iam/docs/service-accounts-create#creating)). Vault is immediately attempting to bind IAM policies after creation, which can sometimes lead to errors. The GCP docs recommend using an exponential backoff retry with a jitter. This PR adds a retry mechanism that attempts to get the service account within the exponential retry, and once the get request succeeds, we go ahead and attempt to bind the IAM policies.

[Google Docs on retry strategy](https://cloud.google.com/iam/docs/retry-strategy)

# Related Issues/Pull Requests
Fixes #237 

# Contributor Checklist
[x] Add relevant docs to upstream Vault repository, or sufficient reasoning why docs won’t be added yet
[My Docs PR Link](link)
[Example](https://github.com/hashicorp/vault/commit/2715f5cec982aabc7b7a6ae878c547f6f475bba6)
[x] Add output for any tests not ran in CI to the PR description (eg, acceptance tests)
[x] Backwards compatible

Output from acceptance tests:
```
=== RUN   TestRetry
=== PAUSE TestRetry
=== CONT  TestRetry
=== RUN   TestRetry/First_try_success
--- PASS: TestRetry/First_try_success (0.00s)
=== RUN   TestRetry/Three_retries
=== PAUSE TestRetry/Three_retries
=== CONT  TestRetry/Three_retries
--- PASS: TestRetry/Three_retries (0.00s)
=== RUN   TestRetry/Error_on_attempt
=== PAUSE TestRetry/Error_on_attempt
=== CONT  TestRetry/Error_on_attempt
--- PASS: TestRetry/Error_on_attempt (0.00s)
=== RUN   TestRetry/Timeout
=== PAUSE TestRetry/Timeout
=== CONT  TestRetry/Timeout
--- PASS: TestRetry/Timeout (10.00s)
=== RUN   TestRetry/Cancellation
=== PAUSE TestRetry/Cancellation
=== CONT  TestRetry/Cancellation
--- PASS: TestRetry/Cancellation (1.00s)
--- PASS: TestRetry (0.00s)
PASS
```

### CODE REVIEW

File: plugin/role_set.go [hunk 1]
```diff
@@ -166,6 +169,32 @@ func (b *backend) saveRoleSetWithNewAccount(ctx context.Context, req *logical.Re
...
+	// Service accounts in GCP are eventually consistent, and can take over 60s
+	// to be ready for use. Attempt to GET the service account in a retry loop
+	// to ensure the service account is ready for use before continuing on
+	// and creating IAM bindings.
+	_, err = retryWithExponentialBackoff(ctx, func() (interface{}, bool, error) {
+		iamAdmin, err := b.IAMAdminClient(req.Storage)
+		if err != nil {
+			return nil, false, err
+		}
+		gcpAcct, err := b.getServiceAccount(iamAdmin, &gcputil.ServiceAccountId{
```
Comment (fairclothjm) [inline plugin/role_set.go:181]: Are there other API calls that we should retry?

**Review by fairclothjm — DISMISSED** [review]
LGTM! Nothing blocking just some questions/thoughts.

File: plugin/role_set.go [hunk 2]
```diff
@@ -166,6 +169,32 @@ func (b *backend) saveRoleSetWithNewAccount(ctx context.Context, req *logical.Re
...
+
+		return gcpAcct, true, err
+	})
+
+	if err != nil {
+		return nil, fmt.Errorf("error getting service account after creation: %w", err)
+	}
+
 	// Create new IAM bindings.
 	if err := b.createIamBindings(ctx, req, sa.Email, newResources.bindings); err != nil {
```
Comment (vinay-gopalan) [inline plugin/role_set.go:199]: Is it better to just retry this function instead? Or does it make more sense to ensure a service account can be retrieved?

File: plugin/role_set.go [hunk 3]
```diff
@@ -166,6 +169,32 @@ func (b *backend) saveRoleSetWithNewAccount(ctx context.Context, req *logical.Re
...
+		if err != nil {
+			return nil, false, err
+		}
+		gcpAcct, err := b.getServiceAccount(iamAdmin, &gcputil.ServiceAccountId{
+			Project:   sa.ProjectId,
+			EmailOrId: sa.Email,
+		})
+
+		// Propagation delays within GCP can cause this error occasionally, so don't quit on it.
+		if err != nil && (strings.Contains(err.Error(), errDoesNotExist)) {
```
[the remark this answers is not in the document]
Comment (vinay-gopalan) [reply plugin/role_set.go]: Good call! Checking for all documented error codes now

File: plugin/role_set.go (hunk 1 above)
Comment (TJM) [reply plugin/role_set.go:186]: This looks like it will solve our issue. Is there a docker image I can point to for testing/validation?

Comment (fairclothjm) [reply plugin/role_set.go:186]: @TJM This was released yesterday as [v0.21.2](https://github.com/hashicorp/vault-plugin-secrets-gcp/releases/tag/v0.21.2). Please let us know if this solves your issue!

- https://hub.docker.com/r/hashicorp/vault-plugin-secrets-gcp/tags
- https://gallery.ecr.aws/hashicorp/vault-plugin-secrets-gcp
